/*
Copyright 2012-2021 Fastvideo, Ltd. All rights reserved.

Please refer to the Fastvideo Standard License Agreement (SLA), associated
 with this source code for terms and conditions that govern your use of
 this software. Any use, reproduction, disclosure, or distribution of
 this software and related documentation outside the terms of the SLA is strictly prohibited.

IN NO EVENT SHALL FASTVIDEO BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF FASTVIDEO HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

FASTVIDEO SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE AND ACCOMPANYING DOCUMENTATION, IF ANY, PROVIDED HEREUNDER IS PROVIDED "AS IS". FASTVIDEO HAS NO OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
*/

/*Common*/
#define COMPANYNAME "Fastvideo"
#define FASTVIDEO_COPYRIGHT COMPANYNAME " (C) 2012-2021"
#define PRODUCT_VERSION 0,17,0,1
#define PRODUCT_VERSION_S "0.17.0.1"
#define PRODUCT_NAME COMPANYNAME " " "Image & Video Processing SDK"

/*SDK*/
#define SDK_NAME COMPANYNAME " " "Image Processing Library"
#define SDK_NAME_DEMO SDK_NAME " Demo"
#define SDK_NAME_STANDARD_SENSELOCK SDK_NAME " Standard Senselock"
#define SDK_NAME_ENTERPRISE SDK_NAME " Enterprise"
#define SDK_NAME_STANDARD_GUARDANT SDK_NAME " Standard Guardant"
#define SDK_NAME_TRIAL SDK_NAME " Trial"

/*NPP*/

#define NPP_ROTATE COMPANYNAME " NPP Rotate"
#define NPP_ROTATE_VERSION 1,0,1,0
#define NPP_ROTATE_VERSION_S "1.0.1.0"

#define NPP_FILTERS COMPANYNAME " NPP Filters"
#define NPP_FILTERS_VERSION 1,0,1,1
#define NPP_FILTERS_VERSION_S "1.0.1.1"

#define NPP_GEOMETRY COMPANYNAME " NPP Geometry"
#define NPP_GEOMETRY_VERSION 1,1,0,0
#define NPP_GEOMETRY_VERSION_S "1.1.0.0"

#define NPP_RESIZE COMPANYNAME " NPP Resize"
#define NPP_RESIZE_VERSION 1,0,1,0
#define NPP_RESIZE_VERSION_S "1.0.1.0"

#define MJPEG COMPANYNAME " MJPEG"
#define MJPEG_VERSION 1,0,0,0
#define MJPEG_VERSION_S "1.0.0.0"

#define LOSSLESS_JPEG_DECODER COMPANYNAME " Lossless JPEG Decoder"
#define LOSSLESS_JPEG_DECODER_VERSION 1,0,1,0
#define LOSSLESS_JPEG_DECODER_VERSION_S "1.0.1.0"

#define JPEG_12_DECODER COMPANYNAME " JPEG 12 Decoder"
#define JPEG_12_DECODER_VERSION 1,0,0,0
#define JPEG_12_DECODER_VERSION_S "1.0.0.0"

#define EXPERIMENTAL_FILTER COMPANYNAME " Experimental Image Filter"
#define EXPERIMENTAL_FILTER_VERSION 1,0,0,0
#define EXPERIMENTAL_FILTER_VERSION_S "1.0.0.0"

#define J2K_FFMPEG_DECODER COMPANYNAME " J2K FFMPEG Decoder"
#define J2K_FFMPEG_DECODER_VERSION 1,0,0,0
#define J2K_FFMPEG_DECODER_VERSION_S "1.0.0.0"

#define H264 COMPANYNAME " H264"
#define H264_VERSION 1,0,0,0
#define H264_VERSION_S "1.0.0.0"

/*J2K Encoder*/
#define J2K_ENCODER COMPANYNAME " J2K Encoder"
#define J2K_ENCODER_DEMO J2K_ENCODER " Demo"
#define J2K_ENCODER_STANDARD_SENSELOCK J2K_ENCODER " Standard Senselock"
#define J2K_ENCODER_STANDARD_GUARDANT J2K_ENCODER " Standard Guardant"
#define J2K_ENCODER_ENTERPRISE J2K_ENCODER " Enterprise"
#define J2K_ENCODER_TRIAL J2K_ENCODER " Trial"
#define J2K_ENCODER_VERSION 3,0,4,1
#define J2K_ENCODER_VERSION_S "3.0.4.1"

#define DENOISE COMPANYNAME " Denoise"
#define DENOISE_VERSION 1,0,0,0
#define DENOISE_VERSION_S "1.0.0.0"

#define J2K_DECODER COMPANYNAME " J2K Decoder"
#define J2K_DECODER_VERSION 5,5,0,1
#define J2K_DECODER_VERSION_S "5.5.0.1"
#define J2K_DECODER_STANDARD_GUARDANT J2K_DECODER " Standard Guardant"

#define DEBAYER_ENHANCE COMPANYNAME " Debayer Enhance"
#define DEBAYER_ENHANCE_VERSION 1,0,0,0
#define DEBAYER_ENHANCE_VERSION_S "1.0.0.0"

#define CUSTOM_TRANSFORM COMPANYNAME " Custom Transform"
#define CUSTOM_TRANSFORM_VERSION 1,0,0,0
#define CUSTOM_TRANSFORM_VERSION_S "1.0.0.0"

#define DEBAYER_CPU COMPANYNAME " Debayer Enhance"
#define DEBAYER_CPU_VERSION 1,0,0,0
#define DEBAYER_CPU_VERSION_S "1.0.0.0"

#define RESIZE_DEMO COMPANYNAME " CUDA Resize Demo"
#define JPEG_DEMO COMPANYNAME " CUDA JPEG Demo"
#define J2K_DEMO COMPANYNAME " CUDA JPEG 2000 Demo"
#define DEBAYER_DEMO COMPANYNAME " CUDA Debayer Demo"
